[package]
name = "build-content-pack"
version = "0.1.0"
edition = "2024"
description = "Build SMAPI content packs from source files"
repository = "https://github.com/Esper89/stardew-build-content-pack"
license = "AGPL-3.0-only"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[dependencies]
anyhow = "1.0"
bitvec = "1.1"
caseless = "0.2"
clap = { version = "4.6", features = ["derive"] }
file-id = "0.2"
oxipng = "10.1"
png = "0.18"
resvg = "0.47"
serde_json = "1.0"
serde-transcode = "1.1"
toml = { version = "1.1", features = ["preserve_order"] }
unicode-normalization = "0.1"
unicode-segmentation = "1.13"
zip = { version = "8.6", default-features = false, features = ["deflate", "time"] }
